name: Deploy Javadoc and Publish Package

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Publish Package to GitHub Packages
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew publish -Pversion=${{ github.ref_name }}

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: XDTesting Print Directory Structure
        uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2

      - name: Publish Javadoc to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone --branch javadoc https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r build/docs/javadoc/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update Javadoc for ${{ github.ref_name }}"
          git push
